// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaBV0xmCbkgT4K84ClcBwmj59KNsVj7fI',
    appId: '1:463779345131:web:7b26421f3fce141b3104ae',
    messagingSenderId: '463779345131',
    projectId: 'app-calculo-imc-2',
    authDomain: 'app-calculo-imc-2.firebaseapp.com',
    storageBucket: 'app-calculo-imc-2.firebasestorage.app',
    measurementId: 'G-D6JH9TMRCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkUi0uBbzMqLZk3c37w5djNp4bwEDEXD8',
    appId: '1:463779345131:android:6ecf30ff22938c3b3104ae',
    messagingSenderId: '463779345131',
    projectId: 'app-calculo-imc-2',
    storageBucket: 'app-calculo-imc-2.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4fd13Zc4Wzzxa5YqstnK54zJaoOr_dMI',
    appId: '1:463779345131:ios:a897dd8715da65f63104ae',
    messagingSenderId: '463779345131',
    projectId: 'app-calculo-imc-2',
    storageBucket: 'app-calculo-imc-2.firebasestorage.app',
    iosBundleId: 'com.example.appImc',
  );
}
